# Generated by Django 4.0.3 on 2022-07-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comlete',
            new_name='complete',
        ),
    ]
