# Generated by Django 4.0.3 on 2022-07-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_comlete_task_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateForm',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date']},
        ),
    ]
